# Generated by Django 3.1.1 on 2020-09-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameround',
            name='tzar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Card_Tzar', to='game_engine.profile'),
        ),
    ]
