# Generated by Django 3.1.1 on 2020-09-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardstore', '0008_auto_20200904_1649'),
        ('game_engine', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoundProfileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='cardstore.WhiteCard')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_engine.profile')),
            ],
        ),
        migrations.AddField(
            model_name='gameround',
            name='players',
            field=models.ManyToManyField(to='game_engine.GameRoundProfileData'),
        ),
    ]
