# Generated by Django 3.1.1 on 2020-09-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardstore', '0008_auto_20200904_1649'),
        ('game_engine', '0002_auto_20200905_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black_cards', models.ManyToManyField(to='cardstore.BlackCard')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_engine.gamesession')),
                ('white_cards', models.ManyToManyField(to='cardstore.WhiteCard')),
            ],
        ),
    ]
