# Generated by Django 3.1.1 on 2020-09-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0003_sessiondeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to='game_engine.profile'),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='tzar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Card_Tzar', to='game_engine.profile'),
        ),
        migrations.AlterField(
            model_name='sessiondeck',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='game_engine.gamesession'),
        ),
    ]
