# Generated by Django 3.1.1 on 2020-09-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardstore', '0008_auto_20200904_1649'),
        ('game_engine', '0004_auto_20200906_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroundprofiledata',
            name='submitted_cards',
            field=models.ManyToManyField(related_name='submitted_cards', to='cardstore.WhiteCard'),
        ),
        migrations.AlterField(
            model_name='gameroundprofiledata',
            name='cards',
            field=models.ManyToManyField(related_name='cards_held', to='cardstore.WhiteCard'),
        ),
    ]
