# Generated by Django 3.1.1 on 2020-09-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_engine', '0004_auto_20200904_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='room',
        ),
    ]
