# Generated by Django 3.1.1 on 2020-09-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardstore', '0008_auto_20200904_1649'),
        ('game_engine', '0005_auto_20200906_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroundprofiledata',
            name='submitted_cards',
        ),
        migrations.CreateModel(
            name='PlayerSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_cards', models.ManyToManyField(related_name='submitted_cards', to='cardstore.WhiteCard')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_engine.profile')),
            ],
        ),
    ]
