# Generated by Django 3.1.1 on 2020-09-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardstore', '0008_auto_20200904_1649'),
        ('game_engine', '0007_auto_20200906_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroundprofiledata',
            name='submitted_cards',
        ),
        migrations.CreateModel(
            name='CardSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_game_round_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_engine.gameroundprofiledata')),
                ('submitted_white_cards', models.ManyToManyField(related_name='submitted_card_set', to='cardstore.WhiteCard')),
            ],
        ),
    ]
