# Generated by Django 3.1.1 on 2020-09-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=200)),
                ('deck', models.CharField(max_length=200)),
                ('pick', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeckMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=500, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('official', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=500)),
                ('icon', models.CharField(max_length=200)),
                ('deck', models.CharField(max_length=200)),
            ],
        ),
    ]
