# Generated by Django 3.1 on 2020-08-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackcard',
            name='package',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitecard',
            name='package',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
