# Generated by Django 3.1 on 2020-08-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardstore', '0004_blackcard_pick'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('official', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
    ]
