# Generated by Django 3.1 on 2020-08-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardstore', '0005_deckmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckmetadata',
            name='id_name',
            field=models.CharField(default='-', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deckmetadata',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
