# Generated by Django 3.1.1 on 2020-09-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardstore', '0007_gameroom_playerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameRoom',
        ),
        migrations.DeleteModel(
            name='PlayerProfile',
        ),
    ]
