# Generated by Django 3.1.1 on 2020-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardstore', '0008_auto_20200904_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blackcard',
            name='id',
        ),
        migrations.RemoveField(
            model_name='whitecard',
            name='id',
        ),
        migrations.AddField(
            model_name='blackcard',
            name='card_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whitecard',
            name='card_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
